# Default detekt configuration:
# https://github.com/detekt/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

formatting:
  MaximumLineLength: # I was not able to silence it in SpectralLinter.REGEX
    active: false